---
#
# Template usage:
#   This template depends on the following stacks.
#   * Database
#   * Authentication

AWSTemplateFormatVersion: 2010-09-09
Description: Surveys CDN
Transform: AWS::Serverless-2016-10-31

###########################################################################################
## Parameters:
###########################################################################################

Parameters:
  RootStackName:
    Type: String
  
  UserDomainName:
    Type: String

  AppDomainName:
    Type: String
    Description: Prefix for resources

  
###########################################################################################
## Conditions:
###########################################################################################

# Conditions:
#   IsProduction:
#     Fn::Equals:
#       - !Ref Environment
#       - prod
#   IsDevelopment:
#     Fn::Equals:
#       - !Ref Environment
#       - dev
  
###########################################################################################
## Resources:
###########################################################################################

Resources:
  RTWOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: CloudFront Origin Access Identity for ${RootStackName}-webapp-domain-name

  RTWWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Fn::ImportValue:
          Fn::Sub: ${RootStackName}-webapp
      PolicyDocument:
        Statement:
        - Action:
          - s3:GetObject
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Fn::ImportValue:
                  Fn::Sub: ${RootStackName}-webapp
              - /*
          Principal:
            CanonicalUser:
              Fn::GetAtt:
              - RTWOriginAccessIdentity
              - S3CanonicalUserId

  RTWDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases: [!Sub '${AppDomainName}']
        Comment: 
          Fn::Sub: ${RootStackName}-distribution
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
          AllowedMethods:
          - GET
          - HEAD
          - DELETE
          - OPTIONS
          - PATCH
          - POST
          - PUT
          TargetOriginId: 
            Fn::Sub: ${RootStackName}-origin
          ViewerProtocolPolicy: redirect-to-https
        Origins:
        - DomainName:
            Fn::ImportValue:
              Fn::Sub: ${RootStackName}-webapp-domain-name
          Id:
            Fn::Sub: ${RootStackName}-origin
          S3OriginConfig:
            OriginAccessIdentity:
              Fn::Sub: origin-access-identity/cloudfront/${RTWOriginAccessIdentity}
        CustomErrorResponses:
        - ErrorCode: 404
          ResponseCode: 200
          ResponsePagePath: /index.html
          ErrorCachingMinTTL: 0
        - ErrorCode: 403
          ResponseCode: 200
          ResponsePagePath: /index.html
          ErrorCachingMinTTL: 0
        ViewerCertificate:
          AcmCertificateArn:
            Fn::ImportValue:
              !Join
                - '-'
                - - !Select [0, !Split ['-', !Ref AWS::StackName]]
                  - !Select [1, !Split ['-', !Ref AWS::StackName]]
                  - !Select [2, !Split ['-', !Ref AWS::StackName]]
                  - 'certificates-UserCertificateArn'
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only

  Route53RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub "${UserDomainName}."
      RecordSets:
      - Name: !Sub '${AppDomainName}'
        Type: A
        AliasTarget:
          DNSName: !GetAtt RTWDistribution.DomainName
          EvaluateTargetHealth: false
          HostedZoneId: Z2FDTNDATAQYW2
 
##############################################
# Outputs
##############################################
Outputs:
  RTWDomain:
    Value:
      Fn::GetAtt:
      - RTWDistribution
      - DomainName
    Export:
      Name:
        Fn::Sub: ${RootStackName}-domain-name

        